### ISSUE TITLE
Async task generated an exception in Folia

### ISSUE THREAD

**Issue by CengJingMiLu** [byteful/LevelTools#44]
```
[12:01:52] [Folia Async Scheduler Thread #1198/WARN]: [LevelTools] Async task for LevelTools v1.4.0.1 generated an exception
java.util.ConcurrentModificationException: null
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1720) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at LevelTools-1.4.0.1.jar/me.byteful.plugin.leveltools.api.block.impl.FileBlockDataManager.save(FileBlockDataManager.java:31) ~[LevelTools-1.4.0.1.jar:?]
	at LevelTools-1.4.0.1.jar/me.byteful.plugin.leveltools.api.scheduler.impl.folia.FoliaScheduler.lambda$asyncTimer$3(FoliaScheduler.java:35) ~[LevelTools-1.4.0.1.jar:?]
	at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217) ~[folia-1.20.6.jar:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by CengJingMiLu** [comment]
but I didn't seem to have any bugs other than hogging logs

**Comment by byteful** [comment]
@milu2048 Did the latest version, v1.4.0.2, fix this issue?
